- hosts: all
  become: yes
  tasks:
    - debug:
        msg:
          - "Created auto inventory"
          - "Run 'ansible-playbook -i .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory playbook.yml' to provision"
