- hosts: all
  tasks:
    - debug:
        msg:
          - "Created auto inventory"
          - "Run 'ansible-playbook -i .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory create-kube-cluster.yml' to provision"
